
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://nci-gdc.github.io
repo_url: https://github.com/nci-gdc/gdc-docs
copyright: "&copy; GDC"
theme_dir: theme
pages:
- Home: index.md
- A:
  - A1: 'A/a1.md'
  - A2: 'A/a2.md'
- B:
  - B1: 'B/b1.md'
  - B2: 'B/b2.md'

